language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-guiqwt python-tables python-matplotlib
install:
  - pip install --use-mirrors https://github.com/rproepp/spykeutils/tarball/develop
  - python setup.py develop
script: xvfb-run -s "-screen 0 1280x1024x24 -noreset" nosetests